-- Databricks notebook source
-- MAGIC %md
-- MAGIC Databricks compute refers to the selection of computing resources available on Databricks to run your data engineering, data science, and analytics workloads. Choose from serverless compute for on-demand scaling, classic compute for customizable resources, or SQL warehouses for optimized analytics.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### Serverless
-- MAGIC
-- MAGIC On-demand, automatically managed compute that scales based on your workload requirements.
-- MAGIC
-- MAGIC | Topic                           | Description                                                                                                                              |
-- MAGIC |---------------------------------|------------------------------------------------------------------------------------------------------------------------------------------|
-- MAGIC | **Serverless compute for notebooks** | Interactive Python and SQL execution in notebooks with automatic scaling and no infrastructure management.                               |
-- MAGIC | **Serverless compute for jobs**      | Run Lakeflow Jobs without configuring or deploying infrastructure. Automatically provisions and scales compute resources.                |
-- MAGIC | **Serverless pipelines**             | Run Lakeflow Spark Declarative Pipelines without configuring or deploying infrastructure. Automatically provisions and scales compute resources. |
-- MAGIC | **Serverless compute limitations**   | Understanding [limitations and requirements for serverless workloads](https://docs.databricks.com/aws/en/compute/serverless/limitations) and supported configurations.                                        |

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### Classic Compute
-- MAGIC
-- MAGIC | Topic                   | Description                                                                                                                              |
-- MAGIC |-------------------------|------------------------------------------------------------------------------------------------------------------------------------------|
-- MAGIC | **Classic compute overview** | Overview of who can access and create classic compute resources.                                                                         |
-- MAGIC | **Configure compute**       | Create and configure compute for interactive data analysis in notebooks or automated workflows with Lakeflow Jobs.                        |
-- MAGIC | **Standard compute**        | Multi-user compute with shared resources for cost-effective collaboration. Lakeguard provides secure user isolation.                      |
-- MAGIC | **Dedicated compute**       | Compute resource assigned to a single user or group.                                                                                     |
-- MAGIC | **Instance pools**          | Pre-configured instances that reduce compute startup time and provide cost savings for frequent workloads.                               |

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## SQL Warehouses
-- MAGIC
-- MAGIC Optimized compute for SQL queries, analytics, and business intelligence workloads with **serverless** or **classic** options. 
-- MAGIC
-- MAGIC ### SQL Warehouses Types
-- MAGIC
-- MAGIC #### Serverless SQL Warehouse
-- MAGIC
-- MAGIC Using the Databricks serverless architecture, a serverless SQL warehouse supports all of the performance features of Databricks SQL. With a serverless SQL warehouse and its performance features, you get:
-- MAGIC
-- MAGIC - Rapid startup time (typically between 2 and 6 seconds).
-- MAGIC - Rapid upscaling to acquire more compute when needed for maintaining low latency.
-- MAGIC - Query admittance is closer to the hardware's limitation than the virtual machine.
-- MAGIC - Quick downscaling to minimize costs when demand is low, providing consistent performance with optimized costs and resources.
-- MAGIC - Choose a serverless SQL warehouse for the best startup performance, the most efficient IO, smarter handling of query demand that varies greatly over time, and rapid autoscaling when query queuing occurs. See Intelligent Workload Management and autoscaling.
-- MAGIC
-- MAGIC A serverless SQL warehouse performs well with these types of workloads:
-- MAGIC
-- MAGIC - ETL
-- MAGIC - Business intelligence
-- MAGIC - Exploratory analysis
-- MAGIC
-- MAGIC #### Pro SQL Warehouse
-- MAGIC
-- MAGIC A pro SQL warehouse supports **Photon** and **Predictive IO**, but does not support Intelligent Workload Management. With a pro SQL warehouse (unlike a serverless SQL warehouse), the compute layer exists in your AWS account account rather than in your Databricks account. Without Intelligent Workload Management, warehouses are less responsive to query demand that varies greatly over time and cannot autoscale as rapidly as a serverless SQL warehouse. A pro SQL warehouse takes several minutes to start up (typically approximately 4 minutes) and scales up and down with less responsiveness than a serverless SQL warehouse. See Queuing and autoscaling logic.
-- MAGIC
-- MAGIC **Use a pro SQL warehouse when:**
-- MAGIC
-- MAGIC - Serverless SQL warehouses are not available in a region.
-- MAGIC
-- MAGIC - You have custom-defined networking and want to connect to databases in your network in the cloud or on-premises for federation or a hybrid-type architecture. For example, use a pro SQL warehouse if you want to put other services into your network such as an event bus or databases, or you want to connect your network to your on-premises network.
-- MAGIC
-- MAGIC #### Classic SQL Warehouse
-- MAGIC
-- MAGIC A classic SQL warehouse supports **Photon** but does not support Predictive IO or Intelligent Workload Management. With a classic SQL warehouse (unlike a serverless SQL warehouse), the compute layer exists in your AWS account account rather than in your Databricks account. Without support for Predictive IO or Intelligent Workload Management, a classic SQL warehouse provides only entry-level performance and less performance than a serverless or a pro SQL warehouse. A classic SQL warehouse also takes several minutes to start up (typically approximately 4 minutes) and scales up and down with less responsiveness than a serverless SQL warehouse. See Queuing and autoscaling logic.
-- MAGIC
-- MAGIC Use a classic SQL warehouse to run interactive queries for data exploration with entry-level performance and Databricks SQL features.
-- MAGIC
-- MAGIC Each SQL warehouse type has different performance capabilities. The following table shows the performance features supported by each SQL warehouse type.
-- MAGIC
-- MAGIC | Warehouse type | Photon Engine | Predictive IO | Intelligent Workload Management  |
-- MAGIC |----------------|---------------|---------------|----------------------------------|
-- MAGIC | Serverless     | X             | X             | X                                |
-- MAGIC | Pro            | X             | X             |                                  |
-- MAGIC | Classic        | X             |               |                                  |
-- MAGIC
-- MAGIC - **Photon:** The built-in vectorized query engine on Databricks. It makes your existing SQL and DataFrame API calls faster and reduces your total cost per workload.
-- MAGIC
-- MAGIC - **Predictive IO:** A suite of features for speeding up selective scan operations in SQL queries. Predictive IO can provide a wide range of speedups.
-- MAGIC
-- MAGIC - **Intelligent workload management (IWM):** A set of features that enhances Databricks SQL Serverless's ability to process large numbers of queries quickly and cost-effectively. Using AI-powered prediction and dynamic management techniques, IWM works to verify that workloads have the right amount of resources quickly. The key difference lies in the AI capabilities in Databricks SQL to respond dynamically to workload demands rather than using static thresholds.